### ISSUE TITLE
kIsWeb, PaintingBinding errors

### ISSUE THREAD

**Issue by rzld** [material-foundation/google-fonts-flutter#10]
Hi,
So I got this error while running the app using google_fonts package.

```
Compiler message:
../flutter/.pub-cache/hosted/pub.dartlang.org/google_fonts-0.1.1/lib/src/google_fonts_base.dart:94:8: Error: Getter not found: 'kIsWeb'.
  if (!kIsWeb) {
       ^^^^^^
../flutter/.pub-cache/hosted/pub.dartlang.org/google_fonts-0.1.1/lib/src/google_fonts_base.dart:105:28: Error: The method 'handleSystemMessage' isn't defined for the class 'PaintingBinding'.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../flutter/packages/flutter/lib/src/painting/binding.dart').
Try correcting the name to the name of an existing method, or defining a method named 'handleSystemMessage'.
  PaintingBinding.instance.handleSystemMessage({'type': 'fontsChange'});
```

flutter doctor -v result: 
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale en-ID)
    • Flutter version 1.12.13+hotfix.5 at /../../../../flutter
    • Framework revision 27321ebbad (26 hours ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc1)
    • Android SDK at /../../Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 10 (API 28) (emulator)
    • iPhone Rizaldi Tri        • 1b72b08e2f936126e48452d373752ba2fb795762 • ios         • iOS 13.2.3
```

Tried this on both emulators and the same errors appeared. My app still runs when I don't use the google_fonts package.

**Comment by RaschMaslasky** [comment]
Hi there. I got the same errors

**Comment by johnsonmh** [comment]
Seems similar to https://github.com/material-foundation/google-fonts-flutter/issues/6, can you try running `flutter upgrade` and trying again?

**Comment by rzld** [comment]
@johnsonmh it's already on latest version (1.12.13+hotfix.5) and running `flutter upgrade` does nothing.

**Comment by johnsonmh** [comment]
OK, thanks for trying that. It's strange, I remember seeing those exact errors when the pub site was running the analyzer on our library with the previous stable release. But as you've said, you tried upgrading, and you're clearly on the current stable.

Is it possible you have two copies of the SDK on your machine? For example, if you've cloned one from the git repo for development, and downloaded another from flutter.dev, it's possible that they're in two locations. 

What happens when you run `which flutter`? You could also try running `flutter clean`, `flutter channel stable` etc. 

Does the same thing happen when you run your app from the command line using `flutter run`? Maybe your IDE is pointing to a different flutter sdk than is in your `PATH`

**Comment by johnsonmh** [comment]
OK, thanks for trying that. It's strange, I remember seeing those exact errors when the pub site was running the analyzer on our library with the previous stable release. But as you've said, you tried upgrading, and you're clearly on the current stable.

Is it possible you have two copies of the SDK on your machine? For example, if you've cloned one from the git repo for development, and downloaded another from flutter.dev, it's possible that they're in two locations. 

What happens when you run `which flutter`? You could also try running `flutter clean`, `flutter channel stable` etc. 

Does the same thing happen when you run your app from the command line using `flutter run`? Maybe your IDE is pointing to a different flutter sdk than is in your `PATH`

**Comment by eliasjtg** [comment]
I had the same problem.

After several attempts with 'flutter clean', 'flutter upgrade' and delete app from device, it work.

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/imac/development/flutter
    • Framework revision 27321ebbad (4 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/imac/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • moto g 6 • ZY3237SCPX • android-arm • Android 9 (API 28)

• No issues found!
```

**Comment by rzld** [comment]
@johnsonmh I think you're right. I did have two versions of Flutter, and at that time the PATH and Android Studio's settings pointed to different directions. I deleted one of them and made sure that both settings are the same, and now it works. Thanks!

**Comment by soroda** [comment]
Thanks :)

**Comment by 03ABDALLAH** [comment]
just try this "google_fonts: 2.1.1" and it will work
