### ISSUE TITLE
[BUG] Missing Proxima Nova and Jost font in 1.1.0

### ISSUE THREAD

**Issue by JSBmanD** [material-foundation/google-fonts-flutter#120]
**Describe the bug**
Now repository doesn't contain Proxima Nova and Jost font.

**Expected behavior**
Contain Jost and Proxima Nova

**Screenshots**
![Screenshot_1600088038](https://user-images.githubusercontent.com/5402335/93088417-884b6a00-f6a2-11ea-940d-60c7fa478228.png)

**Comment by oldpilgrim** [comment]
Same problem here

**Comment by lsalazarm99** [comment]
Were these fonts present? I downloaded 1.0.0 and no "Josh" or "Proxima Nova" font is showed.

**Comment by guidezpl** [comment]
Hi @JSBmanD, Proxima Nova is not a Google Font and Jost is currently available
<img width="995" alt="Screen Shot 2021-12-30 at 13 41 18" src="https://user-images.githubusercontent.com/6655696/147752878-d28e7ea0-ad92-4384-bc51-c8894e7f3bdd.png">

Therefore I'm closing this issue. Please reopen it if this still occurs, with a small code sample so that I can reproduce the issue.
