### ISSUE TITLE
google fonts not applying[BUG]

### ISSUE THREAD

**Issue by zakarianekal** [material-foundation/google-fonts-flutter#121]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Include the contents of your `google_fonts` directory**
Add contents here.

**Screenshots**

**Desktop (please complete the following information if applicable):**

**Smartphone (please complete the following information if applicable):**

**Additional context**

**Comment by AustrisC** [comment]
Experiencing the same problem.

**Comment by llaenowyd** [comment]
I can't tell if this issue covers this problem I'm facing.

I set up the fonts in development but when I deploy the app bundle they don't load.  I tried to set them up dynamically, [here I changed it somewhat](https://github.com/llaenowyd/a110Freecell/commit/4b0afc3aa4149289405f65ffcbdd17a27170db2a#diff-8de410921969b0aecab44abc84ef73a560371aa0f975763fac24f87cc058540d) but it didn't fix the problem, when I install the app from the Play Store it looks like a default, maybe Roboto font. If I launch the app on the Pixel 3 emulator it looks correct, and if I launch it on my device via USB also looks fine.  Somehow the release build app bundle comes out wrong I guess.

I saw in the README you can also download the ttf and include it - along with a kind of chore about conveying the license, but it's not clear if this is required to deploy with google-fonts or if it's just an alternative approach.

Maybe it should already be working and something like config is messed up?

**Comment by Hekhy** [comment]
> I can't tell if this issue covers this problem I'm facing.
> 
> I set up the fonts in development but when I deploy the app bundle they don't load. I tried to set them up dynamically, [here I changed it somewhat](https://github.com/llaenowyd/a110Freecell/commit/4b0afc3aa4149289405f65ffcbdd17a27170db2a#diff-8de410921969b0aecab44abc84ef73a560371aa0f975763fac24f87cc058540d) but it didn't fix the problem, when I install the app from the Play Store it looks like a default, maybe Roboto font. If I launch the app on the Pixel 3 emulator it looks correct, and if I launch it on my device via USB also looks fine. Somehow the release build app bundle comes out wrong I guess.
> 
> I saw in the README you can also download the ttf and include it - along with a kind of chore about conveying the license, but it's not clear if this is required to deploy with google-fonts or if it's just an alternative approach.
> 
> Maybe it should already be working and something like config is messed up?

Exactly the same thing happened to me, at first if it worked for me when compiling the app, but after finishing the app, it no longer worked when I compiled it only in the emulator and when debugging on my mobile, but I realized that as I said a guy on a stackoverflow post, googlefonts needs to connect to the internet. This is strange because without giving permission at the beginning it worked. And thinking why this could happen, I realized that I had installed the chewie package and this player needs you to give it internet permissions, but I had not given them because it still worked well for me since I used a video locally. Even so I tried to give it internet permissions and this solved the problem with googlefonts and everything worked perfectly. I don't know if it will fix your problem but something like that happened to me and it was solved like that.

**Comment by patelpathik** [comment]
I'm facing same issue, details [here](https://github.com/material-foundation/google-fonts-flutter/issues/169#issue-898478199).

**Comment by patelpathik** [comment]
This [answer](https://stackoverflow.com/a/61755872/11435898) worked for me, don't know why but I haven't added this android permission in another project with same package and platform version, its' working in that case.
