### ISSUE TITLE
Process finished with exit code 1

### ISSUE THREAD

**Issue by pradeep14598** [material-foundation/google-fonts-flutter#214]
Because google_fonts >=2.0.0-nullsafety.0 depends on http ^0.13.0 and news depends on http ^0.12.1, google_fonts >=2.0.0-nullsafety.0 is forbidden.
So, because news depends on google_fonts ^2.2.0, version solving failed.
pub get failed (1; So, because news depends on google_fonts ^2.2.0, version solving failed.)
Process finished with exit code 1

**Comment by devj3ns** [comment]
@pradeep14598 please provide your `pubspec.yaml` file(s).

**Comment by dasirale** [comment]
My output in vscode: 
Because learning_english_app depends on google_fonts >=2.3.1 which requires Flutter SDK version >=2.10.0-0, version solving failed.
pub get failed (1; Because learning_english_app depends on google_fonts >=2.3.1 which requires Flutter SDK version >=2.10.0-0, version solving failed.)
exit code 1"
How to install package? help me

**Comment by guidezpl** [comment]
Please run `flutter doctor -v`. If you're not running Flutter 2.10, you probably need to upgrade with `flutter upgrade`
