### ISSUE TITLE
Support condensed versions of fonts

### ISSUE THREAD

**Issue by guidezpl** [material-foundation/google-fonts-flutter#59]
Fonts like Roboto Condensed are not explicitly listed in the proto response from the generator. 

In that response, it looks like those would be the Roboto fonts with a 0.75 width (there are 300, 400, and 700 versions). I suspect it's not always 0.75 so, should figure out with the fonts team how they treat condensed fonts.

**Comment by GitVVV** [comment]
What is wrong with "RobotoCondensed"? ^0.3.5

**Comment by cytryn** [comment]
You mean `GoogleFonts.robotoCondensedTextTheme()`?

**Comment by guidezpl** [comment]
Hmm, I'm on 0.3.7 and I don't have it
<img width="520" alt="Screenshot 2020-02-10 at 11 28 34" src="https://user-images.githubusercontent.com/6655696/74142116-81ceae80-4bf8-11ea-833e-1f66c1f5590c.png">

**Comment by johnsonmh** [comment]
Thanks for flagging this, we're in the process of updating the fonts.google.com API end point we're hitting, and right now this is resulting in a slightly different set of fonts. For example, all the "condensed" fonts are currently missing.

If you need a "condensed" font, we recommend sticking with version `0.3.4` for the time being, otherwise stay tuned for future versions because we are planning on getting these fonts back.

**Comment by johnsonmh** [comment]
Update: version [0.3.10](https://pub.dev/packages/google_fonts/versions/0.3.10) is live on pub.dev and brings back the "condensed" fonts as their own standalone fonts!
