### ISSUE TITLE
Font LexendDeca/lexendDecaTextTheme missing

### ISSUE THREAD

**Issue by thuette** [material-foundation/google-fonts-flutter#65]
In versions after 0.3.4 GoogleFonts.lexendDecaTextTheme has been removed. Is there a reason it has been removed?

As it has been included before, might you consider re-adding the font? 

Thanks in advance and with best regards,
Thomas

**Comment by johnsonmh** [comment]
Thanks for letting us know! We're updating the API end point we're hitting to get fonts from fonts.google.com, right now that is resulting in a slightly different subset of fonts. 

We _are_ planning on bringing this font back, so stay tuned. Otherwise, you can stick with version `0.3.4` or earlier to continue using the `Lexend Deca` font.

**Comment by johnsonmh** [comment]
Thanks for your patience, version [0.3.10](https://pub.dev/packages/google_fonts/versions/0.3.10) is live and brings back Lexend Deca!
