### ISSUE TITLE
GoogleFonts.roboto looks Condensed

### ISSUE THREAD

**Issue by raviganwal** [material-foundation/google-fonts-flutter#74]
I am using `GoogleFonts.roboto` but output of font looks Condensed.
Code I am using,

`Text('Flutter is awesome', style: GoogleFonts.roboto(fontSize: 18),)`

Output:

![image](https://user-images.githubusercontent.com/22388017/75047585-05d44080-54ed-11ea-8580-c742889b6410.png)

**Comment by hawkinsjb1** [comment]
I'm also getting this bug, but only when I use a bold fontweight in OpenSans

**Comment by RyanSusana** [comment]
I can also confirm that I am getting this bug with Open Sans

**Comment by johnsonmh** [comment]
Thanks for filing this everyone, I believe this should be fixed with https://github.com/material-foundation/google-fonts-flutter/pull/79. Version [0.3.10](https://pub.dev/packages/google_fonts/versions/0.3.10) is live on the pub site, please check out this version to verify that it fixes the issues you're seeing!

**Comment by raviganwal** [comment]
@johnsonmh yes I have checked again and this issue is fixed for me in latest version. Thank you.
